AffirmationTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: AffirmationTable-${self:provider.stage}
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: sort
        AttributeType: S
      - AttributeName: data
        AttributeType: S
    BillingMode: PAY_PER_REQUEST
    KeySchema:
      - AttributeName: id
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: sortAndData
        KeySchema:
          - AttributeName: sort
            KeyType: HASH
          - AttributeName: data
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
